stages:
  - build
  - deploy

variables:
  IMAGE: "${DOCKER_IMAGE}:${CI_COMMIT_SHORT_SHA}"

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""

  before_script:
    - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USER" --password-stdin
  script:
    - docker build -t "$IMAGE" .
    - docker push "$IMAGE"
    - docker tag "$IMAGE" "${DOCKER_IMAGE}:latest" || true
    - docker push "${DOCKER_IMAGE}:latest" || true
  only:
    - staging
  tags:
    - linux
    - vm

deploy:
  stage: deploy
  before_script:
    - apk add --no-cache bash
  script:
    - echo "Desplegando en VM vía runner shell"
    - docker pull "$IMAGE" || true
    - cd /root/proyectos/proyecto-test1 || exit 1
    - "sed -i 's|image: .*|image: ${IMAGE}|g' docker-compose.yml || true"
    - docker-compose -f docker-compose.yml up -d --remove-orphans
    - docker image prune -f
  only:
    - staging
  tags:
    - linux
    - vm
  dependencies:
    - build
