// Code generated by entimport, DO NOT EDIT.

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"
)

type Category struct {
	ent.Schema
}

func (Category) Fields() []ent.Field {
	return []ent.Field{field.Int("id"), field.Int("user_id").Optional(), field.String("name"), field.Enum("type").Values("expense", "income")}
}
func (Category) Edges() []ent.Edge {
	return []ent.Edge{edge.From("user", User.Type).Ref("categories").Unique().Field("user_id"), edge.To("transactions", Transaction.Type)}
}
func (Category) Annotations() []schema.Annotation {
	return nil
}
